package br.com.jcwj.UI;

import br.com.jcwj.util.ConfigAtualizacao;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker.StateValue;


/**
 *
 * @author julio
 */
public class AtualizaTabwinMain extends javax.swing.JFrame {

    private String[] listaEstados;
    /**
     * Creates new form AtualizaTabwinMain
     */
    public AtualizaTabwinMain() {
        this.listaEstados = new String[]{"AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO"};
        initComponents();
        bpGeral.setVisible(false);
        cbEstados.setSelectedIndex(23);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanelTop = new javax.swing.JPanel();
        btAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edPathTabwin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEstados = new javax.swing.JComboBox();
        checkTabwin = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        checkSIH = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        checkSIH2008 = new javax.swing.JCheckBox();
        checkSIH2009 = new javax.swing.JCheckBox();
        checkSIH2010 = new javax.swing.JCheckBox();
        checkSIH2011 = new javax.swing.JCheckBox();
        checkSIH2012 = new javax.swing.JCheckBox();
        checkSIH2013 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        checkSIA = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        checkSIA2008 = new javax.swing.JCheckBox();
        checkSIA2009 = new javax.swing.JCheckBox();
        checkSIA2010 = new javax.swing.JCheckBox();
        checkSIA2011 = new javax.swing.JCheckBox();
        checkSIA2012 = new javax.swing.JCheckBox();
        checkSIA2013 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        checkCIHA = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        checkCIHA2011 = new javax.swing.JCheckBox();
        checkCIHA2012 = new javax.swing.JCheckBox();
        checkCIHA2013 = new javax.swing.JCheckBox();
        btSelPasta = new javax.swing.JButton();
        btExecTabwin = new javax.swing.JButton();
        jPanelBot = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        bpGeral = new javax.swing.JProgressBar();

        fileChooser.setCurrentDirectory(new java.io.File("C:\\"));
            fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Atualizador Tabwin");
            setIconImage(Toolkit.getDefaultToolkit().getImage("icone48.png"));
            setLocationByPlatform(true);
            setName("mainForm"); // NOI18N

            btAtualizar.setText("Atualizar");
            btAtualizar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btAtualizarActionPerformed(evt);
                }
            });

            jLabel1.setText("Pasta Instalação:");

            edPathTabwin.setText("c:\\Tabwin");

            jLabel2.setText("Estado:");

            cbEstados.setModel(new javax.swing.DefaultComboBoxModel(listaEstados));

            checkTabwin.setSelected(true);
            checkTabwin.setText("Instalar/Atualizar o aplicativo Tabwin");

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" SIH (Internações SUS) "));
            jPanel1.setPreferredSize(new java.awt.Dimension(250, 180));

            checkSIH.setSelected(true);
            checkSIH.setText("Atualizar Definições");

            jLabel3.setText("Dados:");

            checkSIH2008.setText("2008");

            checkSIH2009.setText("2009");

            checkSIH2010.setText("2010");

            checkSIH2011.setText("2011");

            checkSIH2012.setSelected(true);
            checkSIH2012.setText("2012");

            checkSIH2013.setSelected(true);
            checkSIH2013.setText("2013");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(checkSIH2008)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIH2009)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIH2010)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIH2011))
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(checkSIH2012)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIH2013))
                        .addComponent(checkSIH))
                    .addContainerGap(32, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(checkSIH)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkSIH2008)
                        .addComponent(checkSIH2009)
                        .addComponent(checkSIH2010)
                        .addComponent(checkSIH2011))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkSIH2012)
                        .addComponent(checkSIH2013)))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(" SIA (Ambulatorial SUS) "));
            jPanel3.setPreferredSize(new java.awt.Dimension(250, 180));

            checkSIA.setSelected(true);
            checkSIA.setText("Atualizar Definições");

            jLabel4.setText("Dados:");

            checkSIA2008.setText("2008");

            checkSIA2009.setText("2009");

            checkSIA2010.setText("2010");

            checkSIA2011.setText("2011");

            checkSIA2012.setSelected(true);
            checkSIA2012.setText("2012");

            checkSIA2013.setSelected(true);
            checkSIA2013.setText("2013");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(checkSIA2012)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIA2013))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(checkSIA2008)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIA2009)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIA2010)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIA2011))
                        .addComponent(checkSIA)
                        .addComponent(jLabel4))
                    .addContainerGap(32, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(checkSIA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkSIA2008))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkSIA2009)
                                .addComponent(checkSIA2010)
                                .addComponent(checkSIA2011))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkSIA2012, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(checkSIA2013, javax.swing.GroupLayout.Alignment.TRAILING)))
            );

            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(" CIHA (dados não-SUS) "));
            jPanel4.setPreferredSize(new java.awt.Dimension(250, 180));

            checkCIHA.setSelected(true);
            checkCIHA.setText("Atualizar Definições");

            jLabel5.setText("Dados:");

            checkCIHA2011.setText("2011");

            checkCIHA2012.setSelected(true);
            checkCIHA2012.setText("2012");

            checkCIHA2013.setSelected(true);
            checkCIHA2013.setText("2013");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(checkCIHA2011)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkCIHA2012)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkCIHA2013))
                        .addComponent(jLabel5)
                        .addComponent(checkCIHA))
                    .addContainerGap(81, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(checkCIHA)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkCIHA2011))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(checkCIHA2012))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(checkCIHA2013)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            btSelPasta.setText("...");
            btSelPasta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSelPastaActionPerformed(evt);
                }
            });

            btExecTabwin.setText("Abrir Tabwin");
            btExecTabwin.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btExecTabwinActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
            jPanelTop.setLayout(jPanelTopLayout);
            jPanelTopLayout.setHorizontalGroup(
                jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTopLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelTopLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkTabwin)
                                .addGroup(jPanelTopLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edPathTabwin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btSelPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btAtualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btExecTabwin))))
                        .addGroup(jPanelTopLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanelTopLayout.setVerticalGroup(
                jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edPathTabwin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btAtualizar)
                        .addComponent(btSelPasta)
                        .addComponent(btExecTabwin))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(checkTabwin)
                    .addGap(5, 5, 5)
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            textLog.setEditable(false);
            textLog.setColumns(20);
            textLog.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
            textLog.setRows(5);
            textLog.setFocusable(false);
            jScrollPane1.setViewportView(textLog);

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Log", jPanel5);

            jCheckBox1.setSelected(true);
            jCheckBox1.setText("Utilizar o ftp msbbs.datasus.gov.br para baixar dados do SIH.");

            jCheckBox2.setText("Baixar arquivos de dados somente se a data do arquivo remoto foi maior que a do arquivo local");

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2))
                    .addContainerGap(290, Short.MAX_VALUE))
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jCheckBox1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox2)
                    .addContainerGap(109, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Configurações", jPanel6);

            javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
            jPanelBot.setLayout(jPanelBotLayout);
            jPanelBotLayout.setHorizontalGroup(
                jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            );
            jPanelBotLayout.setVerticalGroup(
                jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );

            bpGeral.setStringPainted(true);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bpGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bpGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Alterna os controles da Tela entre Ativados e Desativados
     */
    private void alternaControles(boolean estado){
        btAtualizar.setEnabled(estado);
        edPathTabwin.setEnabled(estado);
        btSelPasta.setEnabled(estado);
        checkTabwin.setEnabled(estado);
        checkSIH.setEnabled(estado);
        checkSIA.setEnabled(estado);
        checkCIHA.setEnabled(estado);
        cbEstados.setEnabled(estado);
        checkSIH2008.setEnabled(estado);
        checkSIH2009.setEnabled(estado);
        checkSIH2010.setEnabled(estado);
        checkSIH2011.setEnabled(estado);
        checkSIH2012.setEnabled(estado);
        checkSIH2013.setEnabled(estado);
        checkSIA2008.setEnabled(estado);
        checkSIA2009.setEnabled(estado);
        checkSIA2010.setEnabled(estado);
        checkSIA2011.setEnabled(estado);
        checkSIA2012.setEnabled(estado);
        checkSIA2013.setEnabled(estado);
        checkCIHA2011.setEnabled(estado);
        checkCIHA2012.setEnabled(estado);
        checkCIHA2013.setEnabled(estado);
    }
    
    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed

        jTabbedPane1.setSelectedIndex(0);
        textLog.setText("");
        alternaControles(false);
        
        ConfigAtualizacao config = new ConfigAtualizacao();
        
        config.setPathTabwin(edPathTabwin.getText());
        config.setAtuTabwin(checkTabwin.isSelected());        
        config.setAtuSIH(checkSIH.isSelected());
        config.setAtuSIA(checkSIA.isSelected());
        config.setAtuCIHA(checkCIHA.isSelected());
        config.setUfDados(listaEstados[cbEstados.getSelectedIndex()]);
        
        if (checkSIH2008.isSelected()) { config.addDadosSIH("08"); }
        if (checkSIH2009.isSelected()) { config.addDadosSIH("09"); }
        if (checkSIH2010.isSelected()) { config.addDadosSIH("10"); }
        if (checkSIH2011.isSelected()) { config.addDadosSIH("11"); }
        if (checkSIH2012.isSelected()) { config.addDadosSIH("12"); }
        if (checkSIH2013.isSelected()) { config.addDadosSIH("13"); }
        
        if (checkSIA2008.isSelected()) { config.addDadosSIA("08"); }
        if (checkSIA2009.isSelected()) { config.addDadosSIA("09"); }
        if (checkSIA2010.isSelected()) { config.addDadosSIA("10"); }
        if (checkSIA2011.isSelected()) { config.addDadosSIA("11"); }
        if (checkSIA2012.isSelected()) { config.addDadosSIA("12"); }
        if (checkSIA2013.isSelected()) { config.addDadosSIA("13"); }
        
        if (checkCIHA2011.isSelected()) { config.addDadosCIHA("11"); }
        if (checkCIHA2012.isSelected()) { config.addDadosCIHA("12"); }
        if (checkCIHA2013.isSelected()) { config.addDadosCIHA("13"); }
        
        if (!config.temOpcaoSelecionada()) {
            JOptionPane.showMessageDialog(AtualizaTabwinMain.this, 
                    "Você deve selecionar pelo menos uma das opções de Atualização", "Atualização Tabwin",
                    JOptionPane.INFORMATION_MESSAGE);
            alternaControles(true);
            return;
        }
        
        final AtualizaWorker work = new AtualizaWorker(textLog, config);
        
        work.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(final PropertyChangeEvent event) {
                String nomeProp = event.getPropertyName();
                
                if ("progress".equals(nomeProp)) {
                    bpGeral.setIndeterminate(false);
                    bpGeral.setValue((Integer) event.getNewValue());
                } else if("state".equals(nomeProp)) {
                    switch ((StateValue) event.getNewValue()) {
                    case DONE:
                        bpGeral.setVisible(false);
                        btAtualizar.setEnabled(true);
                        alternaControles(true);
                        try {
                            String termino = work.get();
                            JOptionPane.showMessageDialog(AtualizaTabwinMain.this, "Atualização Concluída", "Atualização Tabwin",
                              JOptionPane.INFORMATION_MESSAGE);
                        } catch (final InterruptedException e) {
                            JOptionPane.showMessageDialog(AtualizaTabwinMain.this, "A atualização foi Cancelada", "Atualização Tabwin",
                                JOptionPane.WARNING_MESSAGE);
                        } catch (final Exception e) {
                            JOptionPane.showMessageDialog(AtualizaTabwinMain.this, "A atualização Falhou. Verifique o log.", "Atualização Tabwin",
                                JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    case STARTED:
                    case PENDING:
                        bpGeral.setVisible(true);
                        bpGeral.setIndeterminate(true);
                        break;
                    }
                    
               } else {
                    
                }
            }
        });
        
        work.execute();
        
    }//GEN-LAST:event_btAtualizarActionPerformed
    
    private void btSelPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelPastaActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (file.isDirectory()) {
                edPathTabwin.setText(file.getAbsolutePath());
            } else {
                edPathTabwin.setText("c:\\Tabwin");
            }
              
            
        }
    }//GEN-LAST:event_btSelPastaActionPerformed

    private void btExecTabwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExecTabwinActionPerformed
        String cmd = edPathTabwin.getText() + "\\TabWin32.exe";
        try {
            Process p = Runtime.getRuntime().exec(cmd);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(AtualizaTabwinMain.this, "Não foi possível executar: " + cmd , "Tabwin",
                                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AtualizaTabwinMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExecTabwinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaTabwinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaTabwinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaTabwinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaTabwinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AtualizaTabwinMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bpGeral;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExecTabwin;
    private javax.swing.JButton btSelPasta;
    private javax.swing.JComboBox cbEstados;
    private javax.swing.JCheckBox checkCIHA;
    private javax.swing.JCheckBox checkCIHA2011;
    private javax.swing.JCheckBox checkCIHA2012;
    private javax.swing.JCheckBox checkCIHA2013;
    private javax.swing.JCheckBox checkSIA;
    private javax.swing.JCheckBox checkSIA2008;
    private javax.swing.JCheckBox checkSIA2009;
    private javax.swing.JCheckBox checkSIA2010;
    private javax.swing.JCheckBox checkSIA2011;
    private javax.swing.JCheckBox checkSIA2012;
    private javax.swing.JCheckBox checkSIA2013;
    private javax.swing.JCheckBox checkSIH;
    private javax.swing.JCheckBox checkSIH2008;
    private javax.swing.JCheckBox checkSIH2009;
    private javax.swing.JCheckBox checkSIH2010;
    private javax.swing.JCheckBox checkSIH2011;
    private javax.swing.JCheckBox checkSIH2012;
    private javax.swing.JCheckBox checkSIH2013;
    private javax.swing.JCheckBox checkTabwin;
    private javax.swing.JTextField edPathTabwin;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea textLog;
    // End of variables declaration//GEN-END:variables
}
